version: '3.4'
services:
  db:
    container_name: smart_tech_db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'smart_tech_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - smart_tech_db_data:/var/lib/mysql
  app:
    container_name: smart_tech_project
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'smart_tech_project'
    restart: unless-stopped
    working_dir: /var/www/html
    ports:  
    - 8000:8000
    # command: sh docker/docker-entrypoint.sh
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
volumes:
  smart_tech_db_data: